"""
USDA Writer

Writes KnowledgePrims to USD ASCII (.usda) format files.
Compatible with Orchestra's KnowledgeRetriever.

Part of USD Cognitive Substrate - Knowledge Prims Distillation.
"""

from __future__ import annotations

import logging
import re
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

from ..schemas import KnowledgePrim
from .config import DistillationConfig

logger = logging.getLogger(__name__)


# USDA file template
USDA_HEADER = '''#usda 1.0
(
    defaultPrim = "Knowledge"
    doc = """
    Distilled Knowledge Prims
    Generated by Orchestra Knowledge Distillation Pipeline
    Source: {source}
    Generated: {timestamp}
    Model: {model}
    Prims: {count}
    """
)

'''

PRIM_TEMPLATE = '''def "Knowledge" (
    kind = "assembly"
)
{{
{prims}
}}
'''

KNOWLEDGE_PRIM_TEMPLATE = '''    def "{name}" (
        doc = "{summary}"
    )
    {{
        custom string content = """{content}"""
        custom string summary = "{summary_escaped}"
        custom float confidence = {confidence}
        custom string provenance = "{provenance}"
        custom string[] domains = [{domains}]
        custom string[] triggers = [{triggers}]
        custom string[] requires = [{requires}]
        custom string[] enables = [{enables}]
        custom string[] related_to = [{related_to}]
        custom string teaching_altitude = "{teaching_altitude}"
        custom string[] key_concepts = [{key_concepts}]
    }}
'''


def _escape_string(s: str) -> str:
    """Escape a string for USDA format.

    Args:
        s: Input string

    Returns:
        Escaped string safe for USDA
    """
    # Escape backslashes first
    s = s.replace("\\", "\\\\")
    # Escape quotes
    s = s.replace('"', '\\"')
    # Remove or escape control characters
    s = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f]", "", s)
    return s


def _escape_multiline(s: str) -> str:
    """Escape a multiline string for triple-quoted USDA content.

    Args:
        s: Input string

    Returns:
        Escaped string safe for triple-quoted blocks
    """
    # Remove null bytes and problematic control chars
    s = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f]", "", s)
    # Escape triple quotes if they appear
    s = s.replace('"""', '\\"\\"\\"')
    return s


def _format_string_array(items: list[str]) -> str:
    """Format a list as USDA string array.

    Args:
        items: List of strings

    Returns:
        Formatted USDA array string
    """
    if not items:
        return ""
    escaped = [f'"{_escape_string(item)}"' for item in items]
    return ", ".join(escaped)


def _path_to_prim_name(path: str) -> str:
    """Convert canonical path to valid prim name.

    Args:
        path: Canonical path like /Knowledge/USD/LIVRPS

    Returns:
        Valid prim name like USD_LIVRPS
    """
    # Remove /Knowledge/ prefix
    name = path.replace("/Knowledge/", "")
    # Replace remaining slashes with underscores
    name = name.replace("/", "_")
    # Remove invalid characters
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    # Ensure starts with letter
    if name and not name[0].isalpha():
        name = "P" + name
    return name or "Unknown"


class USDAWriter:
    """Writes KnowledgePrims to USDA format.

    Attributes:
        config: Distillation configuration
    """

    def __init__(self, config: DistillationConfig) -> None:
        self.config = config
        self._files_written = 0
        self._prims_written = 0

    def write_prims(
        self,
        prims: list[KnowledgePrim],
        output_path: Path | None = None,
        source_name: str = "distillation",
    ) -> Path:
        """Write prims to a USDA file.

        Args:
            prims: List of prims to write
            output_path: Output file path (auto-generated if None)
            source_name: Name of the source corpus

        Returns:
            Path to the written file
        """
        if output_path is None:
            self.config.ensure_directories()
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.config.output_dir / f"distilled_{source_name}_{timestamp}.usda"

        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build USDA content
        usda_content = self._build_usda(prims, source_name)

        # Atomic write: write to temp file, then rename
        # Production Hardening: Prevents partial writes on crash
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                dir=output_path.parent,
                suffix=".usda.tmp",
                delete=False,
                encoding="utf-8",
            ) as f:
                f.write(usda_content)
                temp_path = Path(f.name)

            # Atomic rename (on POSIX; on Windows this replaces)
            temp_path.replace(output_path)

        except Exception as e:
            # Clean up temp file if it exists
            if "temp_path" in locals() and temp_path.exists():
                temp_path.unlink()
            raise

        self._files_written += 1
        self._prims_written += len(prims)

        logger.info(f"Wrote {len(prims)} prims to {output_path}")

        return output_path

    def _build_usda(
        self, prims: list[KnowledgePrim], source_name: str
    ) -> str:
        """Build complete USDA file content.

        Args:
            prims: List of prims
            source_name: Source corpus name

        Returns:
            Complete USDA file content
        """
        # Build header
        header = USDA_HEADER.format(
            source=source_name,
            timestamp=datetime.now().isoformat(),
            model=self.config.model_name,
            count=len(prims),
        )

        # Build individual prim definitions
        prim_defs = []
        for prim in prims:
            prim_def = self._format_prim(prim)
            prim_defs.append(prim_def)

        # Combine into Knowledge container
        body = PRIM_TEMPLATE.format(prims="\n".join(prim_defs))

        return header + body

    def _format_prim(self, prim: KnowledgePrim) -> str:
        """Format a single prim as USDA.

        Args:
            prim: The prim to format

        Returns:
            USDA prim definition string
        """
        name = _path_to_prim_name(prim.canonical_path)

        return KNOWLEDGE_PRIM_TEMPLATE.format(
            name=name,
            summary=_escape_string(prim.summary[:100]),
            content=_escape_multiline(prim.content),
            summary_escaped=_escape_string(prim.summary),
            confidence=prim.confidence,
            provenance=_escape_string(prim.provenance),
            domains=_format_string_array(prim.domains),
            triggers=_format_string_array(prim.triggers),
            requires=_format_string_array(prim.requires),
            enables=_format_string_array(prim.enables),
            related_to=_format_string_array(prim.related_to),
            teaching_altitude=prim.teaching_altitude,
            key_concepts=_format_string_array(prim.key_concepts),
        )

    def write_batch(
        self,
        prim_groups: dict[str, list[KnowledgePrim]],
    ) -> list[Path]:
        """Write multiple groups of prims to separate files.

        DETERMINISM: Processes groups in sorted order for consistent output.
        ThinkingMachines [He2025] batch-invariance compliant.

        Args:
            prim_groups: Dict of source_name -> prims

        Returns:
            List of written file paths
        """
        paths = []

        # Sort keys for deterministic processing order
        for source_name in sorted(prim_groups.keys()):
            prims = prim_groups[source_name]
            if prims:
                path = self.write_prims(prims, source_name=source_name)
                paths.append(path)

        return paths

    def append_to_file(
        self,
        prims: list[KnowledgePrim],
        output_path: Path,
    ) -> None:
        """Append prims to an existing USDA file.

        Note: This is a simplified implementation that rewrites the file.
        For production use, consider proper USD layer composition.

        Args:
            prims: Prims to append
            output_path: Existing USDA file path
        """
        if not output_path.exists():
            self.write_prims(prims, output_path)
            return

        # Read existing content
        existing_content = output_path.read_text(encoding="utf-8")

        # Find the closing brace of the Knowledge def
        # This is a simplified approach - production code should parse properly
        close_idx = existing_content.rfind("}")
        if close_idx < 0:
            logger.warning(f"Could not find closing brace in {output_path}")
            return

        # Insert new prims before the closing brace
        prim_defs = []
        for prim in prims:
            prim_def = self._format_prim(prim)
            prim_defs.append(prim_def)

        new_content = (
            existing_content[:close_idx] +
            "\n" + "\n".join(prim_defs) +
            existing_content[close_idx:]
        )

        # Atomic write for append operation
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                dir=output_path.parent,
                suffix=".usda.tmp",
                delete=False,
                encoding="utf-8",
            ) as f:
                f.write(new_content)
                temp_path = Path(f.name)

            temp_path.replace(output_path)

        except Exception as e:
            if "temp_path" in locals() and temp_path.exists():
                temp_path.unlink()
            raise

        self._prims_written += len(prims)

        logger.info(f"Appended {len(prims)} prims to {output_path}")

    @property
    def stats(self) -> dict[str, Any]:
        """Get writer statistics."""
        return {
            "files_written": self._files_written,
            "prims_written": self._prims_written,
        }
